### ISSUE TITLE
Sections not loading

### ISSUE THREAD

**Issue by juanjotoronja** [SpaceOgre/smarttv-twitch#10]
Games and Streams are working as it should, the Channels front page and Followed Channels are not loading.

**Comment by Fansh1ne** [comment]
Did you enter your username/user id in app/script/config.js ?
Mine is working fine.

**Comment by juanjotoronja** [comment]
@Fansh1ne Yes, app account is showing my username. I'm currently using another fork similar to the one by @nikitakatchik but it doesn't have the "Followed Channels" wich is a nice feature.

**Comment by Fansh1ne** [comment]
I tried others too. This one has both followed channels and working stream info so it's the best one. 

Do you have both username and userid in config? I tried with username only and it wasn't working but when I entered both it's working.

**Comment by SpaceOgre** [comment]
Okay then it might be something wrong with the lookup I do when only username is entered. Will look at it when I get time

**Comment by juanjotoronja** [comment]
@Fansh1ne Tried only with username, i thought that only one was required as both are the same? I'm going to try again if it works with both.

**Comment by SpaceOgre** [comment]
The idea is that it should work with just one off them but something seems to be wrong. I would guess that only userid is required and something is wrong when only username is entered.

**Comment by SpaceOgre** [comment]
Found the bug, don't know when I will be able to fix it but userid needs to be used atm or set to null instead of empty string.

**Comment by juanjotoronja** [comment]
OK now it's working with both username/userid, this fork is better than the one I was using cause stream avatars and info are working plus it has followed channels.
