### ISSUE TITLE
Username - User ID

### ISSUE THREAD

**Issue by Fansh1ne** [SpaceOgre/smarttv-twitch#11]
Tried latest release with username and empty user id and it's not working. With both filled it's all good.

**Comment by SpaceOgre** [comment]
Ah damit, I see now what I missed :(
This is what happens when I don't test enough.

Thank you for testing, will try and get time to fix it soon.

**Comment by SpaceOgre** [comment]
I have fixed it now (I really hope at least). So if you got the time please test the latest master. It is enough to get the SceneBrowser.js

**Comment by Fansh1ne** [comment]
It's working now. Thanks, you're work is much appreciated.

**Comment by SpaceOgre** [comment]
Great! Thanks for testing :)
