### ISSUE TITLE
help for setup development environment

### ISSUE THREAD

**Issue by TiagoAndreAlmeida** [SpaceOgre/smarttv-twitch#16]
i trying to implement new features but i cant make develop environment work, how do you guys use to implement and test on physical tv ? 
by now i just copy source code into usb drive and plug on tv to see if my code work, is to hard and slow.

**Comment by TiagoAndreAlmeida** [comment]
I managed to do a install by the sync app on tv. but not pass from load screen, the app stay loading until exit to default tv channel. on console from eclipse IDE the last log is 
-[AF core] js Loader (3/4).
is some config that i miss to do ?

**Comment by SpaceOgre** [comment]
I have only installed the app from a local webserver using the developer account. Just like the installation steps in the Readme.md

Are you using the Samsung SDK? If so what version?
https://developer.samsung.com/smarttv/develop/tools/tv-extension/archive.html

If you use the SDK it should have an emulator so you can try new things there.

**Comment by TiagoAndreAlmeida** [comment]
i using version 5.1 64bit for linux, i have apache serve for my local webserver, the app install works, maybe on the package process by the IDE have i forget to do something ? i follow the Readme.md and the official tutorial to.

**Comment by SpaceOgre** [comment]
I have not tried the SDK myself so I might not be able to help you much, is it possible to see the Zip that the SDK generates? (Or if it does not is there a manifest or list of included files?)

**Comment by TiagoAndreAlmeida** [comment]
I don't have my pc now,
I will check the files generated by the SDK and get back to you as soon as possible.

**Comment by TiagoAndreAlmeida** [comment]
i check the generate file and seems that what sdk do is only zip package.
the name of file is "TwitchTV_3.9.3_America_20200202.zip".
i put this file on /var/www/html directory together with "widgetlist.xml" file.
this is the widgetlist.xml file content: 
`<?xml version="1.0" encoding="UTF-8"?>
<rsp stat="ok">
<list>

    <widget id="Twitch">
        <title>TwitchTV</title>
        <type>user</type>
        <compression size="103000" type="zip"/>
        <description></description>
        <download>http://192.168.1.8/TwitchTV_3.9.3_America_20200202.zip</download>
    </widget>
</list>
</rsp>`

i will try emulator and see if work on my computer.
worst part is every time i will use the app i have to put the usb device on the tv.

**Comment by TiagoAndreAlmeida** [comment]
hey i think i got this time.
what i trying to do is copy packager file and put on apacher folder, when i set url on eclipser IDE on Window>preferences>Samsung Smart TV>User App Sync Server to /varwww/html the app do not stuck on loading screen more.
i think i will add more steps on Readme for clean this steps for futures mistakes.
