### ISSUE TITLE
Steps to use with your own favorite twitch channels and install

### ISSUE THREAD

**Issue by henriquelbsouza** [SpaceOgre/smarttv-twitch#2]
1- Open the app/script/config.js
2. Replace the current numbers with your own user 
2.1 - I used the following chrome app: https://chrome.google.com/webstore/detail/twitch-username-and-user/laonpoebfalkjijglbjbnkfndibbcoon, otherwise I would have to do a request by hand with a valid client id.
(then install as you would normally do)

## The following steps is just how I installed, maybe it is different for your TV.
3. Create a zip file from the files directly, you can't have a single folder inside.
4. Download SammyWidgets and place it inside the widgets folder.
5. Open SammyWidgets and select Twitch
6. Go to your TV and at the menu, login with the user: "develop" (no password needed)
7. In the apps list, hold the center/enter button in one of the apps, a menu will appear (like the right click ones)
8. Select to configure the IP address
9. Place your computer IP address, must be in the same network I guess.
10. Go to Sync apps or something

Done :)
Your favorites will appear in the APP from now on.

* To the future we could just add some kind of localStorage to save the user's ID and have a new screen that asks for the user name?

If someone knows how to test it in the computer, I can try to do something, otherwise ti would be a pain to install the app every new test :/

**Comment by Resi70** [comment]
![15738279589967568335007080811494](https://user-images.githubusercontent.com/39061122/68950368-4caeed80-07bc-11ea-9807-583ab89349e7.jpg)

**Comment by Resi70** [comment]
![20191115_152743](https://user-images.githubusercontent.com/39061122/68950547-a6afb300-07bc-11ea-941c-15c1dbe79b35.jpg)

**Comment by Resi70** [comment]
![20191115_152743](https://user-images.githubusercontent.com/39061122/68950639-dced3280-07bc-11ea-99d9-64a2119f2364.jpg)

**Comment by Resi70** [comment]
When i try to install this repo on my Samsung UE46ES7000 it starts to install and then i get a error Installation Failed More  information on ...

 With the original i have no problems

![20191115_153135](https://user-images.githubusercontent.com/39061122/68950776-1cb41a00-07bd-11ea-9e69-6ebeecadae51.jpg)

How can i fix this?

**Comment by henriquelbsouza** [comment]
I don't know, did you did a zip file WITHOUT a folder, selecting all files of the project and creating a zip file, like in the described steps?

**Comment by Resi70** [comment]
> I don't know, did you did a zip file WITHOUT a folder, selecting all files of the project and creating a zip file, like in the described steps?

No I did not sorry.  Now i have corrected this and was able to install the app but like the 3.7.1 version from a other repo i get the same error. Unable to load stream data. I did create an api key with the OAuth omleidings-URL's pointing at http://localhost and pasted this api key instead of the old  client id code. I also changed the userid code to my number generated from the extension.

any suggestions.?

**Comment by SpaceOgre** [comment]
Nice guide but it should be in the wiki and not an issue. Will move it when I get time :)
If you have install issues please create a new issue where you state TV model etc

**Comment by henriquelbsouza** [comment]
> > I don't know, did you did a zip file WITHOUT a folder, selecting all files of the project and creating a zip file, like in the described steps?
> 
> No I did not sorry. Now i have corrected this and was able to install the app but like the 3.7.1 version from a other repo i get the same error. Unable to load stream data. I did create an api key with the OAuth omleidings-URL's pointing at http://localhost and pasted this api key instead of the old client id code. I also changed the userid code to my number generated from the extension.
> 
> any suggestions.?

There is at least 2 places that I found that you must change the api key, can you look for all of them and change and check if it works? :)

**Comment by Resi70** [comment]
It does not work. I have change  all keys in Senebrowser.js and Senechannel.js

**Comment by SpaceOgre** [comment]
Closing this now since I have updated the readme
