### ISSUE TITLE
Thanks for fixing 5

### ISSUE THREAD

**Issue by ppzz123** [SpaceOgre/smarttv-twitch#9]
I created an issue (https://github.com/SpaceOgre/smarttv-twitch/issues/5) which you fixed but couldn't thank you because it's closed and Github doesn't support private messages. Thanks for fixing this, it works again and sorry for posting here but I really wanted to thank you. This can be closed.

**Comment by SpaceOgre** [comment]
No problem, happy someone else get to use the things I fix. I think you should be able to post in the closed issue (or it might just be me that can).

**Comment by AlexanderButs** [comment]
Also want to thank you for maintaining this repo and switch over to new twitch api. Original repo is not maintained any more :( Thank you very much for your work :)
